apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: observability-eks
  region: us-east-1

managedNodeGroups:
  - name: observability-node-group
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 30